server:
  contextPath: /hos
  port: 8554
spring:
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/Hospital?createDatabaseIfNotExist=true
    username: prince
    password: Prince212@
    driver-class-name: com.mysql.jdbc.Driver

