server:
  port: 8554
spring:
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/Hospital?createDatabaseIfNotExist=true
    username: root
    password: ramya
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: LEGACYHTML5
